Portfolio popup modal
HSMathebula/HSMathebula.github.io pull request #17
Opened 2022-04-13 11:43 UTC by HSMathebula

##Portfolio

In this project we:

- Add a portfolio modal feature
- Add javaScript for the feature to popup

2022-04-13 13:20 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi Team,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [x] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-13 13:20 UTC, omar-muhamad commented on index.html
> +                    <p class="p-tag">
- [ ] Please remove the popup elements from your HTML file and kindly it suppose to be generated dynamically with javascript so please fix that.

![image](https://user-images.githubusercontent.com/68796232/163188951-95722936-64d9-4a86-8a55-d26b51f482a2.png)

2022-04-13 23:39 UTC, smunozmo approved these changes
Hi @HSMathebula, 👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 👏 👏 👏 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-13 23:46 UTC, merged

2022-04-29 07:39 UTC, khitermedachraf reviewed
**Hello @HSMathebula 👋 you did Amazing work 🥇 .**
Clean Code 👍 .
Github workflow 👍 .
Here are some best practices maybe you can implement to improve your code:

1. it is best practice to begin committing messages with caps so kindly consider that in subsequent commits

1. Also, it is a best practice to use the kebab-case method when creat your name classes. and 

- [ ] keep going, Bro 🔥.